name: creatu_exam
description: Create Exam App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.2
  cloud_firestore: ^4.0.4
  collection: ^1.16.0
  dartz: ^0.10.1
  dio: ^4.0.6
  drift: null
  equatable: ^2.0.5
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_facebook_auth: ^4.4.1+1
  flutter_html: ^2.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^0.23.0
  get_it: ^7.2.0
  go_router: ^6.0.2
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.0
  image_picker: ^0.8.6
  intl: ^0.17.0
  nepali_date_picker: ^5.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  salomon_bottom_bar: ^3.3.1
  sqlite3_flutter_libs: ^0.5.11+1

# dependency_overrides:
#   mocktail: ^0.3.0
dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.3.0
  drift_dev: null
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3

  # mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/

  fonts:
    - family: Monoserrat
      fonts:
        - asset: assets/fonts/Montserrat_Normal_Variable.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_variable_normal.ttf
